dhserv
natsukagami/tet-school-2017 pull request #7
Opened 2017-01-17 17:34 UTC by minhtung0404

2017-01-17 17:36 UTC, phucdtd commented on 20170117/DHSERV.md
> +* Thuật toán tìm đường đi ngắn nhất.
Nói rõ thuật toán nào?

2017-01-17 17:38 UTC, phucdtd commented on 20170117/DHSERV.md
> +* Chúng ta có thể đi từ đỉnh u đến v qua đỉnh s khi mà chỉ khi có cạnh nối giữa u-s và s-v và đỉnh s đã được bật
Chúng ta có thể đi từ đỉnh u đến đỉnh v qua đỉnh s khi và chỉ khi có cạnh nối giữa u-s và s-v, và đỉnh s đã được bật.

2017-01-17 17:41 UTC, phucdtd commented on 20170117/DHSERV.md
> +## Nguyễn Minh Tùng
###[Problem Link](http://vn.spoj.com/problems/DHSERV/)

2017-01-17 17:45 UTC, phucdtd commented on 20170117/DHSERV.md
> + 2.tìm đường đi nhỏ nhất từ u đến v với u, v bất kì nhỏ hơn hoặc bằng n.
Nếu không tồn tại đường đi in ra -1

2017-01-17 17:46 UTC, phucdtd commented on 20170117/DHSERV.md
> + 1.bật đỉnh thứ i.
Truy vấn "1 i" : Bật đỉnh thứ i

2017-01-17 17:46 UTC, phucdtd commented on 20170117/DHSERV.md
> + 2.tìm đường đi nhỏ nhất từ u đến v với u, v bất kì nhỏ hơn hoặc bằng n.
Truy vấn "2 i j": Tính độ dài đường đi ngắn nhất giữa 2 nút i và j

2017-01-18 14:35 UTC, natsukagami commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7#-:-Kam-4VYmeOe92ncH1dN:bnfp4nl)*
<!-- Sent from Reviewable.io -->

2017-01-18 14:37 UTC, natsukagami commented
Em chỉnh lại folder đến file là `20170117/Tuyen/DHSERV.md` nhé, sau đó là merge được rồi.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7#-:-Kam-_zRt65wr0zbpvuY:bgfwfn9)*
<!-- Sent from Reviewable.io -->

2017-01-18 14:42 UTC, phucdtd requested changes
Có vẻ ổn cả rổi đấy

2017-01-18 14:45 UTC, phucdtd requested changes
Last review

2017-01-18 14:45 UTC, phucdtd commented on 20170117/DHSERV.md
> +* http://vn.spoj.com/problems/DHSERV/
chỉnh 1 chút... chỗ này dùng markdown trông cho gọn
```Markdown
[Problem Link](http://vn.spoj.com/problems/DHSERV/)

2017-01-18 14:45 UTC, phucdtd commented on 20170117/DHSERV.md
> +* Chúng ta có thể đi từ đỉnh u đến v qua đỉnh s khi mà chỉ khi có cạnh nối giữa u-s và s-v, và đỉnh s đã được bật. Hay nói một cách khác thì một đường đi giữa hai đỉnh tồn tại khi mà chỉ khi các đỉnh
khi VÀ chỉ khi*

2017-01-18 15:06 UTC, phucdtd commented
*[20170117/DHSERV.md, line 2 at r2](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7#-KahU_L4JYD9DauodiLZ-r2-2:-Kam6AWIEbRiBVEA2EfX:bb6ywmx) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/f2d29304ba4e71273083a327b9673cd346cf6d7b/20170117/DHSERV.md#L2)):*
<details><summary><i>Previously, phucdtd (Hoàng Bảo Phúc) wrote…</i></summary><blockquote>

chỉnh 1 chút... chỗ này dùng markdown trông cho gọn
```Markdown
[Problem Link](http://vn.spoj.com/problems/DHSERV/)
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7)*
<!-- Sent from Reviewable.io -->

2017-01-18 15:06 UTC, phucdtd commented
*[20170117/DHSERV.md, line 10 at r2](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7#-KahU_L4JYD9DauodiLZ-r2-10:-Kam6GR9mpeBlMkYoCsl:bb6ywmx) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/f2d29304ba4e71273083a327b9673cd346cf6d7b/20170117/DHSERV.md#L10)):*
<details><summary><i>Previously, phucdtd (Hoàng Bảo Phúc) wrote…</i></summary><blockquote>

khi VÀ chỉ khi*
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7)*
<!-- Sent from Reviewable.io -->

2017-01-18 15:09 UTC, natsukagami commented
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7)*
<!-- Sent from Reviewable.io -->

2017-01-18 15:12 UTC, natsukagami commented
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7#-Kam7kZKVjAMipHZ4gkj:-Kam7kZKVjAMipHZ4gkk:b-844qzp) (no related file):*
Xóa file cũ đi em

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7)*
<!-- Sent from Reviewable.io -->

2017-01-18 15:12 UTC, natsukagami commented
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7)*
<!-- Sent from Reviewable.io -->

2017-01-18 15:36 UTC, natsukagami commented
Reviewed 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7#-Kam7kZKVjAMipHZ4gkj:-KamDG_8-QTwaMGFenkZ:bnfp4nl) (no related file):*
<details><summary><i>Previously, natsukagami (Natsu Kagami) wrote…</i></summary><blockquote>

Xóa file cũ đi em
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/7)*
<!-- Sent from Reviewable.io -->

2017-01-18 15:37 UTC, merged