Create USACO DEC 09 GOLD COW TOLL PATH.md
natsukagami/tet-school-2017 pull request #8
Opened 2017-01-18 13:36 UTC by hoduchieu01

2017-01-18 14:40 UTC, natsukagami commented
Chỉnh lại đường dẫn file thành `20170117/Khanh/USACO_DEC_09_GOLD_COW_TOLL_PATH.md` nhé.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[USACO DEC 09 GOLD COW TOLL PATH.md, line 14 at r1](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/8#-Kam0I9LWqQsLDT5I0P9:-Kam0I9LWqQsLDT5I0PA:bbxbnkq) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/8cfed633c3163b196fc0fbbdf8007cd46f4726a3/USACO DEC 09 GOLD COW TOLL PATH.md#L14)):*
> ```Markdown
>  Ta sắp xếp các đỉnh theo thứ tự tăng dần theo giá của đỉnh.Tiếp đó sử dụng Floyd để kiểm tra thứ tự sắp xếp của các đỉnh trong đồ thị. Sau đó ta tìm được con đường với giá rẻ nhất và số đỉnh bằng với số đỉnh thứ i trong đồ thị. Như vậy, sau mỗi lần, chúng ta thêm giá đỉnh thứ i vào chi phí cạnh của mỗi con đường và kiểm tra xem có tìm được con đường có giá nhỏ hơn giá đã tìm được không. Con đường với giá rẻ nhất là con đường rẻ nhất của tất cả con đường tìm thấy sau mỗi lần lặp của Floyd.
> 
> ## Conclusion
> ```

Thêm độ phức tạp của thuật toán

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/8#-:-Kam-q7T4fF8fEGRyEyn:bw7exyb)*
<!-- Sent from Reviewable.io -->

2017-01-18 15:28 UTC, phucdtd requested changes
Góp ý cho lần sau: Muốn đánh dấu <= thì ấn "& l e ;" (không có cách và dấu ngoặc kép) (HTML stuff). >= là "& g e ;" Và lần sau viết cách dòng ra tí preview cho dễ =)) TY

2017-01-18 15:28 UTC, phucdtd commented on USACO DEC 09 GOLD COW TOLL PATH.md
> +# USACO DEC 09 GOLD Cow Toll Path
Consider adding this:
```Markdown
###[Problem Link](http://acm.tju.edu.cn/toj/showp3481.html)
```

2017-01-18 15:28 UTC, phucdtd commented on USACO DEC 09 GOLD COW TOLL PATH.md
> + Cho 1 đồ thị có n đỉnh (1<=n<= 250), và m cạnh (m <= 10 000). Mỗi cạnh và mỗi đỉnh của đồ thị đều có giá của nó. Giá của 1 chu trình được tính bằng tổng giá của các cạnh trong chu trình cộng với giá
Chỉnh thành thế này này
```text
Cho 1 đồ thị có n đỉnh (1 &le; n &le; 250), và m cạnh (m &le; 10 000). Mỗi cạnh và mỗi đỉnh của đồ thị đều có giá của nó. Giá của 1 chu trình được tính bằng tổng giá của các cạnh trong chu trình cộng với giá lớn nhất của các đỉnh nó đi qua (tính cả nút bắt đầu và nút kết thúc). Cho k truy vấn (k &le; 10 000), với mỗi truy vấn thứ i hãy in ra giá nhỏ nhất để đi từ đỉnh a<sub>i</sub> đến b<sub>i</sub>.
```
Và đây là cái nó hiện ra:
Cho 1 đồ thị có n đỉnh (1 &le; n &le; 250), và m cạnh (m &le; 10 000). Mỗi cạnh và mỗi đỉnh của đồ thị đều có giá của nó. Giá của 1 chu trình được tính bằng tổng giá của các cạnh trong chu trình cộng với giá lớn nhất của các đỉnh nó đi qua (tính cả nút bắt đầu và nút kết thúc). Cho k truy vấn (k &le; 10 000), với mỗi truy vấn thứ i hãy in ra giá nhỏ nhất để đi từ đỉnh a<sub>i</sub> đến b<sub>i</sub>.

**=> Hãy lợi dụng Markdown và HTML để nghịch lần sau =)**

2017-01-18 15:28 UTC, phucdtd commented on USACO DEC 09 GOLD COW TOLL PATH.md
> +Ta cần một thuật toán để tính chi phí đi lại giữa các đỉnh để tìm giá nhỏ nhất để đi qua các đỉnh. Với (1 <= N <= 250) => thuật toán tìm đường đi ngắn nhất.Floyd là thuật toán ngắn nhất ghép cặp các
Sửa tương tự như trên, <= sửa thành "& l e ;" (không có ngoặc kép và dấu cách)

2017-01-18 15:28 UTC, phucdtd commented on USACO DEC 09 GOLD COW TOLL PATH.md
> +Ta cần một thuật toán để tính chi phí đi lại giữa các đỉnh để tìm giá nhỏ nhất để đi qua các đỉnh. Với (1 <= N <= 250) => thuật toán tìm đường đi ngắn nhất.Floyd là thuật toán ngắn nhất ghép cặp các
Sửa lỗi câu từ.... Đọc hơi lủng củng.
(My opinion)

2017-01-18 15:28 UTC, phucdtd commented on USACO DEC 09 GOLD COW TOLL PATH.md
> + Ta sắp xếp các đỉnh theo thứ tự tăng dần theo giá của đỉnh.Tiếp đó sử dụng Floyd để kiểm tra thứ tự sắp xếp của các đỉnh trong đồ thị. Sau đó ta tìm được con đường với giá rẻ nhất và số đỉnh bằng vớ
Nên chỉ ra thêm vì sao và vẽ hình.
P/s: Có thể tẹo nữa đêm rảnh t ngồi vẽ hình cho.

2017-01-18 15:28 UTC, phucdtd commented on USACO DEC 09 GOLD COW TOLL PATH.md
> +## Conclusion
Chưa có Conclusion

2017-01-18 16:01 UTC, natsukagami commented
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[USACO DEC 09 GOLD COW TOLL PATH.md, line 5 at r1](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/8#-Kalmn04mm5-TTdk7Ndy-r1-5:-KamIZ_lLnmjbPD51UfU:b2pcoui) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/8cfed633c3163b196fc0fbbdf8007cd46f4726a3/USACO DEC 09 GOLD COW TOLL PATH.md#L5)):*
<details><summary><i>Previously, phucdtd (Hoàng Bảo Phúc) wrote…</i></summary><blockquote>

Chỉnh thành thế này này
```text
Cho 1 đồ thị có n đỉnh (1 &le; n &le; 250), và m cạnh (m &le; 10 000). Mỗi cạnh và mỗi đỉnh của đồ thị đều có giá của nó. Giá của 1 chu trình được tính bằng tổng giá của các cạnh trong chu trình cộng với giá lớn nhất của các đỉnh nó đi qua (tính cả nút bắt đầu và nút kết thúc). Cho k truy vấn (k &le; 10 000), với mỗi truy vấn thứ i hãy in ra giá nhỏ nhất để đi từ đỉnh a<sub>i</sub> đến b<sub>i</sub>.
```
Và đây là cái nó hiện ra:
Cho 1 đồ thị có n đỉnh (1 &le; n &le; 250), và m cạnh (m &le; 10 000). Mỗi cạnh và mỗi đỉnh của đồ thị đều có giá của nó. Giá của 1 chu trình được tính bằng tổng giá của các cạnh trong chu trình cộng với giá lớn nhất của các đỉnh nó đi qua (tính cả nút bắt đầu và nút kết thúc). Cho k truy vấn (k &le; 10 000), với mỗi truy vấn thứ i hãy in ra giá nhỏ nhất để đi từ đỉnh a<sub>i</sub> đến b<sub>i</sub>.

**=> Hãy lợi dụng Markdown và HTML để nghịch lần sau =)**
</blockquote></details>

Không cần quá trọng trình bày như này đâu :smile:

---

*[USACO DEC 09 GOLD COW TOLL PATH.md, line 9 at r1](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/8#-Kalmn04mm5-TTdk7Ndy-r1-9:-KamIkmxKOCGXhA_h-xl:b6km14b) ([raw file](https://github.com/natsukagami/tet-school-2017/blob/8cfed633c3163b196fc0fbbdf8007cd46f4726a3/USACO DEC 09 GOLD COW TOLL PATH.md#L9)):*
> Không cần quá trọng trình bày như này đâu 😄

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/8)*
<!-- Sent from Reviewable.io -->

2017-01-18 16:02 UTC, phucdtd commented
Vì 1 thế giới có những bài chữa dễ nhìn, dễ hiểu =)) Sửa cx có mất bao lâu đâu a, chỉ cần Replace all là được. Tại chúng nó ko biết HTML nên hơi mệt =))

2017-01-18 16:05 UTC, natsukagami commented
Anh nghĩ là mình cũng chỉ cần giữ cái phần trình bày không cần thực sự chăm chút quá (nếu không đã bắt viết LateX rồi, dại gì đi làm từng cái HTML như này, phân số thì viết làm sao được). Kiểu như <= với &le; thì cũng khá dễ nhìn như nhau thôi, ai cũng quen rồi mà, với lại code thì phải dùng <= chứ làm gì có &le; mà dùng :smile:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/natsukagami/tet-school-2017/8#-:-KamJOEwd4P2DWJaNvRp:b4lsyer)*
<!-- Sent from Reviewable.io -->

2017-01-18 16:12 UTC, phucdtd commented
e dùng latex toàn fail... ko hiểu sao e ko dùng đc, cái frac thì ok thôi nhưng exponent ko chơi đc

2017-01-19 16:37 UTC, natsukagami commented
@hoduchieu01 em merge `patch-3` vào `patch-1` là được nhé, đừng mở PR mới.

2023-07-03 13:06 UTC, closed without merging